services:
  aspnotes:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - 8080:8080
    volumes:
      - db_data:/app/db
    user: root
volumes:
  db_data:
